# ackermann parameters
 ackermann_control:

  # Trajectory TXT in config foulder
  file: "traj_parking.txt"

  # Select platform to run
  # 1 - Simulator
  # 2 - Robot
  platform: 1


  # Frequency in Hz for publish Torque
  torque_frequency: 20.0
  steer_angle_frequency: 10.0


  # Backstepping Controller Parameters
  controller:
    vel_k: 10
    vel_c1: 5
    vel_c2: 5
    vel_Ts: 0.02
    vel_etol: 0.1
    orie_k: 12.0
    orie_c1: 3.0
    orie_c2: 3.0
    orie_Ts: 0.02
    orie_etol: 0.05

  # PID Controller Parameters
  pid_controller:
    kp: 50 #20.7 #14.7
    ki: 40 #17 #6.3
    kd: 0 #3.1 #5.1
    ts: 0.02
    etol: 0.01
    ori_kp: 20 #17
    ori_ki: 18 #14
    ori_kd: 3 #5
    ori_ts: 0.02
    ori_etol: 0.05


  # Dynamics parameters
  dynamics:
    mass: 50.0
    gravity: 9.81
    drag: 0.3279
    wheel_radio: 0.08
    motor_efficiency: 0.95
    friction_coef: 0.3
    inertial_coef: 0.03898
    cr: 500
    cf: 500
    lf: 0.3
    lr: 0.3
    inertia_z: 1.4211
